FIELD_TYPES = {
    'CharField': 'text',
    'TextField': 'text',
    'RichTextField': 'text',
    'SlugField': 'string',
    'IntegerField': 'int',
    'BigIntegerField': 'bigint',
    'FileField': 'string',
    'ImageField': 'string',
    'ForeignKey': 'multi',
    'ManyToOneRel': 'multi',
    'FloatField': 'float',
    'BooleanField': 'bool',
    'DateTimeField': 'timestamp',
    'DateField': 'timestamp',
    'JSONField': 'json',
}

ALLOWED_TABLE_PARAMS = [
    'morphology',
    'morphology_skip_fields',
    'min_stemming_len',
    'wordforms',
    'stopwords',
    'stopword_step',
    'stopwords_unstemmed',
    'exceptions',
    'index_exact_words',
    'expand_keywords',
    'charset_table',
    'min_word_len',
    'blend_mode',
    'blend_chars',
]
